module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'auth',
        'marketplace',
        'construction',
        'erp',
        'crm',
        'contractor',
        'materials',
        'buyer',
        'engineer',
        'admin',
        'ai',
        'shared',
        'ui',
        'types',
        'utils',
        'config',
        'infra',
        'db',
        'api',
        'web',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
  },
}
